spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # PRODUCTION: Frissítsd a saját domain nevedre!
          # Példa: https://auth.varganet.cloud
          issuer-uri: https://auth.varganet.cloud/realms/biometric-2fa
          jwk-set-uri: https://auth.varganet.cloud/realms/biometric-2fa/protocol/openid-connect/certs

logging:
  level:
    org.springframework.security: WARN
    org.springframework.web.cors: ERROR
